// ─── Default Monster Library ──────────────────────────────────────────────────
// These monsters are pre-loaded into the app and cannot be deleted.
// They are identified by IDs prefixed with "default-".
// Users can edit copies of them when added to an encounter.

export const DEFAULT_MONSTERS = [

  // ── CR 0 ──────────────────────────────────────────────────────────────────

  {
    id: 'default-rat',
    isDefault: true,
    name: 'Rat',
    type: 'Beast',
    cr: '0',
    hp: 1,
    hpFormula: '1d4-1',
    ac: 10,
    speed: 20,
    abilities: { str: 2, dex: 11, con: 9, int: 2, wis: 10, cha: 4 },
    attacks: [
      { id: 'rat-bite', name: 'Bite', hitBonus: 0, damage: '1', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Smell: advantage on Perception checks that rely on smell.',
  },
  {
    id: 'default-bat',
    isDefault: true,
    name: 'Bat',
    type: 'Beast',
    cr: '0',
    hp: 1,
    hpFormula: '1d4-1',
    ac: 12,
    speed: 30,
    abilities: { str: 2, dex: 15, con: 8, int: 2, wis: 12, cha: 4 },
    attacks: [
      { id: 'bat-bite', name: 'Bite', hitBonus: 0, damage: '1', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Echolocation, Keen Hearing. Blind beyond 60 ft in darkness without echolocation.',
  },
  {
    id: 'default-cat',
    isDefault: true,
    name: 'Cat',
    type: 'Beast',
    cr: '0',
    hp: 2,
    hpFormula: '1d4',
    ac: 12,
    speed: 40,
    abilities: { str: 3, dex: 15, con: 10, int: 3, wis: 12, cha: 7 },
    attacks: [
      { id: 'cat-claws', name: 'Claws', hitBonus: 0, damage: '1', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Smell: advantage on Perception checks that rely on smell.',
  },
  {
    id: 'default-commoner',
    isDefault: true,
    name: 'Commoner',
    type: 'Humanoid',
    cr: '0',
    hp: 4,
    hpFormula: '1d8',
    ac: 10,
    speed: 30,
    abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
    attacks: [
      { id: 'commoner-club', name: 'Club', hitBonus: 2, damage: '1d4', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: '',
  },
  {
    id: 'default-crawling-claw',
    isDefault: true,
    name: 'Crawling Claw',
    type: 'Undead',
    cr: '0',
    hp: 2,
    hpFormula: '1d4',
    ac: 12,
    speed: 20,
    abilities: { str: 13, dex: 14, con: 11, int: 5, wis: 10, cha: 4 },
    attacks: [
      { id: 'claw-claw', name: 'Claw', hitBonus: 3, damage: '1d4+1', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Undead Nature: does not need air, food, drink, or sleep.',
  },

  // ── CR 1/8 ────────────────────────────────────────────────────────────────

  {
    id: 'default-bandit',
    isDefault: true,
    name: 'Bandit',
    type: 'Humanoid',
    cr: '0.125',
    hp: 11,
    hpFormula: '2d8+2',
    ac: 12,
    speed: 30,
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    attacks: [
      { id: 'bandit-scimitar', name: 'Scimitar', hitBonus: 3, damage: '1d6+1', damageType: 'slashing', notes: '' },
      { id: 'bandit-crossbow', name: 'Heavy Crossbow', hitBonus: 3, damage: '1d10+1', damageType: 'piercing', notes: 'Range 100/400 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: '',
  },
  {
    id: 'default-cultist',
    isDefault: true,
    name: 'Cultist',
    type: 'Humanoid',
    cr: '0.125',
    hp: 9,
    hpFormula: '2d8',
    ac: 12,
    speed: 30,
    abilities: { str: 11, dex: 12, con: 10, int: 10, wis: 11, cha: 10 },
    attacks: [
      { id: 'cultist-scimitar', name: 'Scimitar', hitBonus: 3, damage: '1d6+1', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Dark Devotion: advantage on saving throws against being charmed or frightened.',
  },
  {
    id: 'default-giant-rat',
    isDefault: true,
    name: 'Giant Rat',
    type: 'Beast',
    cr: '0.125',
    hp: 7,
    hpFormula: '2d6',
    ac: 12,
    speed: 30,
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    attacks: [
      { id: 'grat-bite', name: 'Bite', hitBonus: 4, damage: '1d4+2', damageType: 'piercing', notes: 'DC 11 Con save or poisoned until start of next turn' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Smell: advantage on Perception checks that rely on smell.',
  },
  {
    id: 'default-kobold',
    isDefault: true,
    name: 'Kobold Warrior',
    type: 'Humanoid',
    cr: '0.125',
    hp: 5,
    hpFormula: '2d6-2',
    ac: 12,
    speed: 30,
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    attacks: [
      { id: 'kobold-dagger', name: 'Dagger', hitBonus: 4, damage: '1d4+2', damageType: 'piercing', notes: '' },
      { id: 'kobold-sling', name: 'Sling', hitBonus: 4, damage: '1d4+2', damageType: 'bludgeoning', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Pack Tactics: advantage on attack rolls when an ally is adjacent to the target. Sunlight Sensitivity: disadvantage on attack rolls and Perception in sunlight.',
  },
  {
    id: 'default-merfolk',
    isDefault: true,
    name: 'Merfolk',
    type: 'Humanoid',
    cr: '0.125',
    hp: 11,
    hpFormula: '2d8+2',
    ac: 11,
    speed: 10,
    abilities: { str: 10, dex: 13, con: 12, int: 11, wis: 11, cha: 12 },
    attacks: [
      { id: 'merfolk-spear', name: 'Spear', hitBonus: 2, damage: '1d6', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Amphibious: can breathe air and water. Swim speed 40 ft.',
  },
  {
    id: 'default-skeleton',
    isDefault: true,
    name: 'Skeleton',
    type: 'Undead',
    cr: '0.25',
    hp: 13,
    hpFormula: '2d8+4',
    ac: 13,
    speed: 30,
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    attacks: [
      { id: 'skel-shortsword', name: 'Shortsword', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
      { id: 'skel-shortbow', name: 'Shortbow', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: 'Range 80/320 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Vulnerable to bludgeoning. Immune to poison and exhaustion. Cannot be poisoned, charmed, or frightened.',
  },

  // ── CR 1/4 ────────────────────────────────────────────────────────────────

  {
    id: 'default-axe-beak',
    isDefault: true,
    name: 'Axe Beak',
    type: 'Beast',
    cr: '0.25',
    hp: 19,
    hpFormula: '3d10+3',
    ac: 11,
    speed: 50,
    abilities: { str: 14, dex: 12, con: 12, int: 2, wis: 10, cha: 5 },
    attacks: [
      { id: 'axebeak-beak', name: 'Beak', hitBonus: 4, damage: '1d8+2', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: '',
  },
  {
    id: 'default-giant-bat',
    isDefault: true,
    name: 'Giant Bat',
    type: 'Beast',
    cr: '0.25',
    hp: 22,
    hpFormula: '4d10',
    ac: 13,
    speed: 10,
    abilities: { str: 15, dex: 16, con: 11, int: 2, wis: 12, cha: 6 },
    attacks: [
      { id: 'gbat-bite', name: 'Bite', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Echolocation, Keen Hearing. Fly speed 60 ft.',
  },
  {
    id: 'default-giant-centipede',
    isDefault: true,
    name: 'Giant Centipede',
    type: 'Beast',
    cr: '0.25',
    hp: 4,
    hpFormula: '1d6+1',
    ac: 13,
    speed: 30,
    abilities: { str: 5, dex: 14, con: 12, int: 1, wis: 7, cha: 3 },
    attacks: [
      { id: 'gcent-bite', name: 'Bite', hitBonus: 4, damage: '1d4+2', damageType: 'piercing', notes: 'DC 11 Con save or 3d6 poison damage and paralyzed for up to 1 min' },
    ],
    spellSlots: {},
    spells: [],
    notes: '',
  },
  {
    id: 'default-goblin',
    isDefault: true,
    name: 'Goblin Warrior',
    type: 'Humanoid',
    cr: '0.25',
    hp: 7,
    hpFormula: '2d6',
    ac: 15,
    speed: 30,
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    attacks: [
      { id: 'gob-scimitar', name: 'Scimitar', hitBonus: 4, damage: '1d6+2', damageType: 'slashing', notes: '' },
      { id: 'gob-shortbow', name: 'Shortbow', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: 'Range 80/320 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Nimble Escape: can Disengage or Hide as a bonus action.',
  },
  {
    id: 'default-mud-mephit',
    isDefault: true,
    name: 'Mud Mephit',
    type: 'Elemental',
    cr: '0.25',
    hp: 27,
    hpFormula: '6d6+6',
    ac: 11,
    speed: 20,
    abilities: { str: 8, dex: 12, con: 12, int: 9, wis: 11, cha: 7 },
    attacks: [
      { id: 'mud-fists', name: 'Fists', hitBonus: 1, damage: '1d6-1', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'False Appearance: looks like mud pile when motionless. Mud Breath (Recharge 6): DC 11 Dex save or restrained for 1 minute. Fly speed 20 ft, Swim speed 20 ft.',
  },
  {
    id: 'default-poisonous-snake',
    isDefault: true,
    name: 'Poisonous Snake',
    type: 'Beast',
    cr: '0.125',
    hp: 2,
    hpFormula: '1d4',
    ac: 13,
    speed: 30,
    abilities: { str: 2, dex: 16, con: 11, int: 1, wis: 10, cha: 3 },
    attacks: [
      { id: 'psnake-bite', name: 'Bite', hitBonus: 5, damage: '1d4+3', damageType: 'piercing', notes: 'DC 10 Con save or 2d4 poison damage' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Swim speed 30 ft.',
  },
  {
    id: 'default-stirge',
    isDefault: true,
    name: 'Stirge',
    type: 'Beast',
    cr: '0.125',
    hp: 2,
    hpFormula: '1d4',
    ac: 14,
    speed: 10,
    abilities: { str: 4, dex: 16, con: 11, int: 2, wis: 8, cha: 6 },
    attacks: [
      { id: 'stirge-bite', name: 'Blood Drain', hitBonus: 5, damage: '1d4+3', damageType: 'piercing', notes: 'Attaches on hit. While attached, deals 1d4+3 at start of each turn. DC 10 Str check to detach.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Fly speed 40 ft.',
  },
  {
    id: 'default-twig-blight',
    isDefault: true,
    name: 'Twig Blight',
    type: 'Plant',
    cr: '0.125',
    hp: 4,
    hpFormula: '1d6+1',
    ac: 13,
    speed: 20,
    abilities: { str: 6, dex: 13, con: 12, int: 4, wis: 8, cha: 3 },
    attacks: [
      { id: 'twig-claws', name: 'Claws', hitBonus: 3, damage: '1d4+1', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'False Appearance: motionless looks like dead shrub. Vulnerable to fire. Immune to blindness, deafness.',
  },
  {
    id: 'default-zombie',
    isDefault: true,
    name: 'Zombie',
    type: 'Undead',
    cr: '0.25',
    hp: 22,
    hpFormula: '3d8+9',
    ac: 8,
    speed: 20,
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    attacks: [
      { id: 'zombie-slam', name: 'Slam', hitBonus: 3, damage: '1d6+1', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Undead Fortitude: when reduced to 0 HP by damage other than radiant, DC 5+damage Con save. Success: drop to 1 HP instead.',
  },

  // ── CR 1/2 ────────────────────────────────────────────────────────────────

  {
    id: 'default-ape',
    isDefault: true,
    name: 'Ape',
    type: 'Beast',
    cr: '0.5',
    hp: 19,
    hpFormula: '3d8+6',
    ac: 12,
    speed: 30,
    abilities: { str: 16, dex: 14, con: 14, int: 6, wis: 12, cha: 7 },
    attacks: [
      { id: 'ape-fist', name: 'Fist', hitBonus: 5, damage: '1d6+3', damageType: 'bludgeoning', notes: '' },
      { id: 'ape-rock', name: 'Rock', hitBonus: 5, damage: '1d6+3', damageType: 'bludgeoning', notes: 'Range 25/50 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Climb speed 30 ft.',
  },
  {
    id: 'default-black-bear',
    isDefault: true,
    name: 'Black Bear',
    type: 'Beast',
    cr: '0.5',
    hp: 19,
    hpFormula: '3d8+6',
    ac: 11,
    speed: 40,
    abilities: { str: 15, dex: 10, con: 14, int: 2, wis: 12, cha: 7 },
    attacks: [
      { id: 'bbear-bite', name: 'Bite', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
      { id: 'bbear-claws', name: 'Claws', hitBonus: 4, damage: '2d6+2', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Smell: advantage on Perception checks that rely on smell. Climb speed 30 ft.',
  },
  {
    id: 'default-cockatrice',
    isDefault: true,
    name: 'Cockatrice',
    type: 'Monstrosity',
    cr: '0.5',
    hp: 27,
    hpFormula: '6d6+6',
    ac: 11,
    speed: 20,
    abilities: { str: 6, dex: 12, con: 12, int: 2, wis: 13, cha: 5 },
    attacks: [
      { id: 'cock-beak', name: 'Beak', hitBonus: 3, damage: '1d4+1', damageType: 'piercing', notes: 'DC 11 Con save or petrified in 24 hours unless cured' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Fly speed 40 ft.',
  },
  {
    id: 'default-crocodile',
    isDefault: true,
    name: 'Crocodile',
    type: 'Beast',
    cr: '0.5',
    hp: 19,
    hpFormula: '3d10+3',
    ac: 12,
    speed: 20,
    abilities: { str: 15, dex: 10, con: 13, int: 2, wis: 10, cha: 5 },
    attacks: [
      { id: 'croc-bite', name: 'Bite', hitBonus: 4, damage: '1d10+2', damageType: 'piercing', notes: 'Target grappled (DC 12 escape). While grappled: restrained, croc can bite only grappled target.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Hold Breath: 15 minutes. Swim speed 30 ft.',
  },
  {
    id: 'default-giant-wasp',
    isDefault: true,
    name: 'Giant Wasp',
    type: 'Beast',
    cr: '0.5',
    hp: 13,
    hpFormula: '3d8',
    ac: 12,
    speed: 10,
    abilities: { str: 10, dex: 14, con: 10, int: 1, wis: 10, cha: 3 },
    attacks: [
      { id: 'gwasp-sting', name: 'Sting', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: 'DC 11 Con save or 2d6 poison damage and poisoned for 1 minute' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Fly speed 50 ft.',
  },
  {
    id: 'default-hobgoblin',
    isDefault: true,
    name: 'Hobgoblin Warrior',
    type: 'Humanoid',
    cr: '0.5',
    hp: 11,
    hpFormula: '2d8+2',
    ac: 18,
    speed: 30,
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    attacks: [
      { id: 'hob-longsword', name: 'Longsword', hitBonus: 3, damage: '1d8+1', damageType: 'slashing', notes: '' },
      { id: 'hob-longbow', name: 'Longbow', hitBonus: 3, damage: '1d8+1', damageType: 'piercing', notes: 'Range 150/600 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Martial Advantage: once per turn, deal extra 2d6 damage if ally is within 5 ft of target.',
  },
  {
    id: 'default-needle-blight',
    isDefault: true,
    name: 'Needle Blight',
    type: 'Plant',
    cr: '0.25',
    hp: 11,
    hpFormula: '2d8+2',
    ac: 12,
    speed: 30,
    abilities: { str: 12, dex: 12, con: 13, int: 4, wis: 8, cha: 3 },
    attacks: [
      { id: 'nblight-claws', name: 'Claws', hitBonus: 3, damage: '1d6+1', damageType: 'piercing', notes: '' },
      { id: 'nblight-needles', name: 'Needles', hitBonus: 3, damage: '2d6+1', damageType: 'piercing', notes: 'Range 30/60 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'False Appearance: motionless looks like dead shrub. Immune to blindness, deafness.',
  },
  {
    id: 'default-orc',
    isDefault: true,
    name: 'Orc',
    type: 'Humanoid',
    cr: '0.5',
    hp: 15,
    hpFormula: '2d8+6',
    ac: 13,
    speed: 30,
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    attacks: [
      { id: 'orc-greataxe', name: 'Greataxe', hitBonus: 5, damage: '1d12+3', damageType: 'slashing', notes: '' },
      { id: 'orc-javelin', name: 'Javelin', hitBonus: 5, damage: '1d6+3', damageType: 'piercing', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Aggressive: bonus action to move up to speed toward a hostile.',
  },
  {
    id: 'default-shadow',
    isDefault: true,
    name: 'Shadow',
    type: 'Undead',
    cr: '0.5',
    hp: 16,
    hpFormula: '3d8+3',
    ac: 12,
    speed: 40,
    abilities: { str: 6, dex: 14, con: 13, int: 6, wis: 10, cha: 8 },
    attacks: [
      { id: 'shadow-drain', name: 'Strength Drain', hitBonus: 4, damage: '2d6+2', damageType: 'necrotic', notes: 'Target\'s Strength reduced by 1d4. If Str reaches 0, target dies and rises as Shadow.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Amorphous: can move through 1-inch space. Shadow Stealth: hide as bonus action in dim light/darkness. Vulnerable to radiant. Immune to necrotic, poison. Cannot be exhausted, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained.',
  },
  {
    id: 'default-warhorse',
    isDefault: true,
    name: 'Warhorse',
    type: 'Beast',
    cr: '0.5',
    hp: 19,
    hpFormula: '3d10+3',
    ac: 11,
    speed: 60,
    abilities: { str: 18, dex: 12, con: 13, int: 2, wis: 12, cha: 7 },
    attacks: [
      { id: 'horse-hooves', name: 'Hooves', hitBonus: 6, damage: '2d6+4', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Trampling Charge: if horse moves 20 ft straight and hits, target DC 14 Str save or knocked prone. If prone, hooves as bonus action.',
  },
  {
    id: 'default-wolf',
    isDefault: true,
    name: 'Wolf',
    type: 'Beast',
    cr: '0.25',
    hp: 11,
    hpFormula: '2d8+2',
    ac: 13,
    speed: 40,
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    attacks: [
      { id: 'wolf-bite', name: 'Bite', hitBonus: 4, damage: '2d4+2', damageType: 'piercing', notes: 'DC 11 Str save or knocked prone' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Hearing and Smell. Pack Tactics: advantage on attack rolls when an ally is adjacent to target.',
  },

  // ── CR 1 ──────────────────────────────────────────────────────────────────

  {
    id: 'default-brown-bear',
    isDefault: true,
    name: 'Brown Bear',
    type: 'Beast',
    cr: '1',
    hp: 34,
    hpFormula: '4d10+12',
    ac: 11,
    speed: 40,
    abilities: { str: 19, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    attacks: [
      { id: 'bbear-bite2', name: 'Bite', hitBonus: 6, damage: '1d8+4', damageType: 'piercing', notes: '' },
      { id: 'bbear-claws2', name: 'Claws', hitBonus: 6, damage: '2d6+4', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Smell: advantage on Perception checks that rely on smell. Multiattack: Claws + Bite.',
  },
  {
    id: 'default-bugbear',
    isDefault: true,
    name: 'Bugbear',
    type: 'Humanoid',
    cr: '1',
    hp: 27,
    hpFormula: '5d8+5',
    ac: 16,
    speed: 30,
    abilities: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    attacks: [
      { id: 'bug-morningstar', name: 'Morningstar', hitBonus: 4, damage: '2d8+2', damageType: 'piercing', notes: '' },
      { id: 'bug-javelin', name: 'Javelin', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Brute: melee attacks deal one extra die of damage (included). Surprise Attack: extra 2d6 damage if target is surprised.',
  },
  {
    id: 'default-dryad',
    isDefault: true,
    name: 'Dryad',
    type: 'Fey',
    cr: '1',
    hp: 22,
    hpFormula: '5d8',
    ac: 11,
    speed: 30,
    abilities: { str: 10, dex: 12, con: 11, int: 14, wis: 15, cha: 20 },
    attacks: [
      { id: 'dryad-club', name: 'Club', hitBonus: 2, damage: '1d4', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: { 1: 2 },
    spells: [],
    notes: 'Innate Spellcasting (CHA, DC 14): Druidcraft at will; Entangle, Goodberry (2/day). Tree Stride: teleport between trees up to 500 ft. Magic Resistance: advantage on saves against spells.',
  },
  {
    id: 'default-fire-snake',
    isDefault: true,
    name: 'Fire Snake',
    type: 'Elemental',
    cr: '1',
    hp: 22,
    hpFormula: '5d8',
    ac: 14,
    speed: 30,
    abilities: { str: 12, dex: 14, con: 11, int: 7, wis: 10, cha: 8 },
    attacks: [
      { id: 'fsnake-bite', name: 'Bite', hitBonus: 3, damage: '1d4+1', damageType: 'piercing', notes: 'Plus 1d4 fire damage' },
      { id: 'fsnake-tail', name: 'Tail', hitBonus: 3, damage: '1d6+1', damageType: 'bludgeoning', notes: 'Plus 1d4 fire damage' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Heated Body: creatures that touch or hit with melee take 1d6 fire damage. Immune to fire.',
  },
  {
    id: 'default-ghoul',
    isDefault: true,
    name: 'Ghoul',
    type: 'Undead',
    cr: '1',
    hp: 22,
    hpFormula: '5d8',
    ac: 12,
    speed: 30,
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    attacks: [
      { id: 'ghoul-bite', name: 'Bite', hitBonus: 2, damage: '2d6', damageType: 'piercing', notes: '' },
      { id: 'ghoul-claws', name: 'Claws', hitBonus: 4, damage: '2d4+2', damageType: 'slashing', notes: 'DC 10 Con save or paralyzed for 1 min (repeat save each turn). Elves immune.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Bite + Claws. Immune to charm, exhaustion, poison.',
  },
  {
    id: 'default-giant-spider',
    isDefault: true,
    name: 'Giant Spider',
    type: 'Beast',
    cr: '1',
    hp: 26,
    hpFormula: '4d10+4',
    ac: 14,
    speed: 30,
    abilities: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    attacks: [
      { id: 'gspider-bite', name: 'Bite', hitBonus: 5, damage: '1d8+3', damageType: 'piercing', notes: 'DC 11 Con save or 2d8 poison damage (half on save), and poisoned for 1 hour if failed by 5+' },
      { id: 'gspider-web', name: 'Web (Recharge 5–6)', hitBonus: 5, damage: '0', damageType: 'bludgeoning', notes: 'Range 30/60 ft. Target DC 12 Dex save or restrained. DC 12 Str check to break free.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Spider Climb: can climb difficult surfaces. Web Sense: knows position of any creature in contact with same web. Web Walker: ignores movement restrictions from webs.',
  },
  {
    id: 'default-goblin-boss',
    isDefault: true,
    name: 'Goblin Boss',
    type: 'Humanoid',
    cr: '1',
    hp: 21,
    hpFormula: '6d6',
    ac: 17,
    speed: 30,
    abilities: { str: 10, dex: 14, con: 10, int: 10, wis: 8, cha: 10 },
    attacks: [
      { id: 'gboss-scimitar', name: 'Scimitar', hitBonus: 4, damage: '1d6+2', damageType: 'slashing', notes: '' },
      { id: 'gboss-javelin', name: 'Javelin', hitBonus: 2, damage: '1d6', damageType: 'piercing', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Nimble Escape. Redirect Attack: when missed, redirect to adjacent goblin ally. Multiattack: 2× Scimitar.',
  },
  {
    id: 'default-harpy',
    isDefault: true,
    name: 'Harpy',
    type: 'Monstrosity',
    cr: '1',
    hp: 38,
    hpFormula: '7d8+7',
    ac: 11,
    speed: 20,
    abilities: { str: 12, dex: 13, con: 12, int: 7, wis: 10, cha: 13 },
    attacks: [
      { id: 'harp-claws', name: 'Claws', hitBonus: 3, damage: '2d4+1', damageType: 'slashing', notes: '' },
      { id: 'harp-club', name: 'Club', hitBonus: 3, damage: '1d4+1', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Luring Song: creatures within 300 ft DC 11 Wis save or charmed and incapacitated, must move toward harpy. Multiattack: Claws + Club. Fly speed 40 ft.',
  },
  {
    id: 'default-imp',
    isDefault: true,
    name: 'Imp',
    type: 'Fiend',
    cr: '1',
    hp: 10,
    hpFormula: '3d4+3',
    ac: 13,
    speed: 20,
    abilities: { str: 6, dex: 17, con: 13, int: 11, wis: 12, cha: 14 },
    attacks: [
      { id: 'imp-sting', name: 'Sting (Tail)', hitBonus: 5, damage: '1d4+3', damageType: 'piercing', notes: 'DC 11 Con save or 3d6 poison damage (half on save)' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Shapechanger: rat, raven, spider. Devil\'s Sight: see through magical darkness 120 ft. Magic Resistance. Fly speed 40 ft. Immune to fire, poison. Resistant to cold, nonmagical weapon damage.',
  },
  {
    id: 'default-quasit',
    isDefault: true,
    name: 'Quasit',
    type: 'Fiend',
    cr: '1',
    hp: 7,
    hpFormula: '3d4',
    ac: 13,
    speed: 40,
    abilities: { str: 5, dex: 17, con: 10, int: 7, wis: 10, cha: 10 },
    attacks: [
      { id: 'quas-claws', name: 'Claws', hitBonus: 4, damage: '1d4+3', damageType: 'piercing', notes: 'DC 10 Con save or poisoned for 1 min (repeat save each turn)' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Shapechanger: bat, centipede, toad. Magic Resistance. Scare (3/day): one creature within 20 ft DC 10 Wis save or frightened for 1 min. Resistant to cold, fire, lightning, nonmagical weapons. Immune to poison.',
  },

  // ── CR 2 ──────────────────────────────────────────────────────────────────

  {
    id: 'default-ankheg',
    isDefault: true,
    name: 'Ankheg',
    type: 'Monstrosity',
    cr: '2',
    hp: 39,
    hpFormula: '6d10+6',
    ac: 14,
    speed: 30,
    abilities: { str: 17, dex: 11, con: 13, int: 1, wis: 13, cha: 6 },
    attacks: [
      { id: 'ankheg-bite', name: 'Bite', hitBonus: 5, damage: '2d6+3', damageType: 'slashing', notes: 'Plus 1d6 acid. Target grappled (DC 13 escape). While grappled: restrained, ankheg can bite only grappled target.' },
      { id: 'ankheg-spit', name: 'Acid Spray (Recharge 6)', hitBonus: 0, damage: '3d6', damageType: 'acid', notes: '30 ft line. DC 13 Dex save, half on success. Only if no grappled creature.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Burrow speed 10 ft.',
  },
  {
    id: 'default-bandit-captain',
    isDefault: true,
    name: 'Bandit Captain',
    type: 'Humanoid',
    cr: '2',
    hp: 65,
    hpFormula: '10d8+20',
    ac: 15,
    speed: 30,
    abilities: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    attacks: [
      { id: 'bcap-scimitar', name: 'Scimitar', hitBonus: 5, damage: '1d6+3', damageType: 'slashing', notes: '' },
      { id: 'bcap-dagger', name: 'Dagger', hitBonus: 5, damage: '1d4+3', damageType: 'piercing', notes: 'Range 20/60 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: 3 attacks — 2× Scimitar + 1× Dagger. Parry: +2 AC reaction when hit.',
  },
  {
    id: 'default-berserker',
    isDefault: true,
    name: 'Berserker',
    type: 'Humanoid',
    cr: '2',
    hp: 67,
    hpFormula: '9d8+27',
    ac: 13,
    speed: 30,
    abilities: { str: 16, dex: 12, con: 17, int: 9, wis: 11, cha: 9 },
    attacks: [
      { id: 'bers-greataxe', name: 'Greataxe', hitBonus: 5, damage: '1d12+3', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Reckless: at start of turn, can attack with advantage until start of next turn, but attacks against you also have advantage.',
  },
  {
    id: 'default-cultist-fanatic',
    isDefault: true,
    name: 'Cultist Fanatic',
    type: 'Humanoid',
    cr: '2',
    hp: 33,
    hpFormula: '6d8+6',
    ac: 13,
    speed: 30,
    abilities: { str: 11, dex: 14, con: 12, int: 10, wis: 13, cha: 14 },
    attacks: [
      { id: 'cfan-dagger', name: 'Dagger', hitBonus: 4, damage: '1d4+2', damageType: 'piercing', notes: '' },
    ],
    spellSlots: { 1: 4, 2: 2 },
    spells: [],
    notes: 'Dark Devotion: advantage on saves vs charm and frighten. Multiattack: 2× Dagger. Spellcasting (WIS DC 12, +4): Inflict Wounds, Command, Hold Person.',
  },
  {
    id: 'default-dire-wolf',
    isDefault: true,
    name: 'Dire Wolf',
    type: 'Beast',
    cr: '1',
    hp: 37,
    hpFormula: '5d10+10',
    ac: 14,
    speed: 50,
    abilities: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    attacks: [
      { id: 'dwolf-bite', name: 'Bite', hitBonus: 5, damage: '2d6+3', damageType: 'piercing', notes: 'DC 13 Str save or knocked prone' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Keen Hearing and Smell. Pack Tactics: advantage on attack rolls when an ally is adjacent to target.',
  },
  {
    id: 'default-ettercap',
    isDefault: true,
    name: 'Ettercap',
    type: 'Monstrosity',
    cr: '2',
    hp: 44,
    hpFormula: '8d8+8',
    ac: 13,
    speed: 30,
    abilities: { str: 14, dex: 15, con: 13, int: 7, wis: 12, cha: 8 },
    attacks: [
      { id: 'etter-bite', name: 'Bite', hitBonus: 4, damage: '1d8+2', damageType: 'piercing', notes: 'Plus 1d8 poison. DC 11 Con save or poisoned for 1 min.' },
      { id: 'etter-claws', name: 'Claws', hitBonus: 4, damage: '2d4+2', damageType: 'slashing', notes: '' },
      { id: 'etter-web', name: 'Web (Recharge 5–6)', hitBonus: 4, damage: '0', damageType: 'bludgeoning', notes: 'Range 30/60 ft. DC 11 Str save or restrained. DC 11 Str check to break free.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Bite + Claws. Spider Climb. Web Sense. Web Walker.',
  },
  {
    id: 'default-gargoyle',
    isDefault: true,
    name: 'Gargoyle',
    type: 'Elemental',
    cr: '2',
    hp: 52,
    hpFormula: '7d8+21',
    ac: 15,
    speed: 30,
    abilities: { str: 15, dex: 11, con: 16, int: 6, wis: 11, cha: 7 },
    attacks: [
      { id: 'garg-bite', name: 'Bite', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
      { id: 'garg-claws', name: 'Claws', hitBonus: 4, damage: '1d6+2', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Bite + Claws. False Appearance: motionless looks like stone statue. Fly speed 60 ft. Resistant to nonmagical weapon damage. Immune to poison, exhaustion.',
  },
  {
    id: 'default-gelatinous-cube',
    isDefault: true,
    name: 'Gelatinous Cube',
    type: 'Ooze',
    cr: '2',
    hp: 84,
    hpFormula: '8d10+40',
    ac: 6,
    speed: 15,
    abilities: { str: 14, dex: 3, con: 20, int: 1, wis: 6, cha: 1 },
    attacks: [
      { id: 'gcube-pseudo', name: 'Pseudopod', hitBonus: 4, damage: '3d6', damageType: 'acid', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Engulf: creature in cube\'s space DC 12 Dex save or engulfed — restrained, blinded, takes 6d6 acid at start of each turn, DC 12 Str check to escape. Transparent: DC 15 Perception to notice when motionless. Ooze Cube: occupies full 10-ft cube. Immune to blindness, charmed, deafened, frightened, prone.',
  },
  {
    id: 'default-ghast',
    isDefault: true,
    name: 'Ghast',
    type: 'Undead',
    cr: '2',
    hp: 36,
    hpFormula: '8d8',
    ac: 13,
    speed: 30,
    abilities: { str: 16, dex: 17, con: 10, int: 11, wis: 10, cha: 8 },
    attacks: [
      { id: 'ghast-bite', name: 'Bite', hitBonus: 3, damage: '2d8+3', damageType: 'piercing', notes: '' },
      { id: 'ghast-claws', name: 'Claws', hitBonus: 5, damage: '2d6+3', damageType: 'slashing', notes: 'DC 10 Con save or paralyzed for 1 min. Elves immune.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Bite + Claws. Stench: creatures within 5 ft DC 10 Con save or poisoned until start of next turn (immune for 24h on success). Turning Defiance: advantage on saves against Turn Undead. Immune to charm, exhaustion, poison.',
  },
  {
    id: 'default-giant-boar',
    isDefault: true,
    name: 'Giant Boar',
    type: 'Beast',
    cr: '2',
    hp: 42,
    hpFormula: '5d10+15',
    ac: 12,
    speed: 40,
    abilities: { str: 17, dex: 10, con: 16, int: 2, wis: 7, cha: 5 },
    attacks: [
      { id: 'gboar-tusk', name: 'Tusk', hitBonus: 5, damage: '2d6+3', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Charge: if moves 20+ ft and hits with tusk, target DC 13 Str save or knocked prone. If prone, bonus action tusk attack. Relentless (Recharges after Short/Long Rest): if taking 10 or fewer damage that would reduce to 0 HP, drop to 1 HP instead.',
  },
  {
    id: 'default-gnoll',
    isDefault: true,
    name: 'Gnoll',
    type: 'Humanoid',
    cr: '0.5',
    hp: 22,
    hpFormula: '5d8',
    ac: 15,
    speed: 30,
    abilities: { str: 14, dex: 12, con: 11, int: 6, wis: 10, cha: 7 },
    attacks: [
      { id: 'gnoll-bite', name: 'Bite', hitBonus: 4, damage: '1d4+2', damageType: 'piercing', notes: '' },
      { id: 'gnoll-spear', name: 'Spear', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
      { id: 'gnoll-bow', name: 'Longbow', hitBonus: 3, damage: '1d8+1', damageType: 'piercing', notes: 'Range 150/600 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Rampage: when reduced to 0 HP by melee, gnoll can move up to half speed and bite as bonus action.',
  },
  {
    id: 'default-grick',
    isDefault: true,
    name: 'Grick',
    type: 'Monstrosity',
    cr: '2',
    hp: 27,
    hpFormula: '6d8',
    ac: 14,
    speed: 30,
    abilities: { str: 14, dex: 14, con: 11, int: 3, wis: 14, cha: 5 },
    attacks: [
      { id: 'grick-tentacles', name: 'Tentacles', hitBonus: 4, damage: '2d6+2', damageType: 'slashing', notes: '' },
      { id: 'grick-beak', name: 'Beak', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Tentacles + Beak. Stone Camouflage: advantage on Stealth in rocky terrain. Resistant to nonmagical weapon damage. Climb speed 30 ft.',
  },
  {
    id: 'default-hobgoblin-captain',
    isDefault: true,
    name: 'Hobgoblin Captain',
    type: 'Humanoid',
    cr: '3',
    hp: 52,
    hpFormula: '8d8+16',
    ac: 17,
    speed: 30,
    abilities: { str: 15, dex: 14, con: 14, int: 12, wis: 10, cha: 13 },
    attacks: [
      { id: 'hcap-greatsword', name: 'Greatsword', hitBonus: 4, damage: '2d6+2', damageType: 'slashing', notes: '' },
      { id: 'hcap-javelin', name: 'Javelin', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: 2× Greatsword. Martial Advantage: once per turn extra 3d6 damage when ally adjacent to target. Leadership (Recharges after Short/Long Rest): bonus action to bolster allies within 30 ft — add 1d4 to one attack or save.',
  },
  {
    id: 'default-lizardfolk',
    isDefault: true,
    name: 'Lizardfolk',
    type: 'Humanoid',
    cr: '0.5',
    hp: 22,
    hpFormula: '4d8+4',
    ac: 15,
    speed: 30,
    abilities: { str: 15, dex: 10, con: 13, int: 7, wis: 12, cha: 7 },
    attacks: [
      { id: 'lizard-bite', name: 'Bite', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: '' },
      { id: 'lizard-claws', name: 'Claws', hitBonus: 4, damage: '1d4+2', damageType: 'slashing', notes: '' },
      { id: 'lizard-javelin', name: 'Javelin', hitBonus: 4, damage: '1d6+2', damageType: 'piercing', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Bite + Claws or 2× Javelin. Hold Breath: 15 min. Swim speed 30 ft.',
  },
  {
    id: 'default-ogre',
    isDefault: true,
    name: 'Ogre',
    type: 'Giant',
    cr: '2',
    hp: 59,
    hpFormula: '7d10+21',
    ac: 11,
    speed: 40,
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    attacks: [
      { id: 'ogre-greatclub', name: 'Greatclub', hitBonus: 6, damage: '2d8+4', damageType: 'bludgeoning', notes: '' },
      { id: 'ogre-javelin', name: 'Javelin', hitBonus: 6, damage: '2d6+4', damageType: 'piercing', notes: 'Range 30/120 ft' },
    ],
    spellSlots: {},
    spells: [],
    notes: '',
  },
  {
    id: 'default-polar-bear',
    isDefault: true,
    name: 'Polar Bear',
    type: 'Beast',
    cr: '2',
    hp: 42,
    hpFormula: '5d10+15',
    ac: 12,
    speed: 40,
    abilities: { str: 20, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    attacks: [
      { id: 'pbear-bite', name: 'Bite', hitBonus: 7, damage: '1d8+5', damageType: 'piercing', notes: '' },
      { id: 'pbear-claws', name: 'Claws', hitBonus: 7, damage: '2d6+5', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Claws + Bite. Keen Smell: advantage on Perception via smell. Swim speed 30 ft.',
  },
  {
    id: 'default-priest',
    isDefault: true,
    name: 'Priest',
    type: 'Humanoid',
    cr: '2',
    hp: 27,
    hpFormula: '5d8+5',
    ac: 13,
    speed: 30,
    abilities: { str: 10, dex: 10, con: 12, int: 13, wis: 16, cha: 13 },
    attacks: [
      { id: 'priest-mace', name: 'Mace', hitBonus: 2, damage: '1d6', damageType: 'bludgeoning', notes: '' },
    ],
    spellSlots: { 1: 4, 2: 3 },
    spells: [],
    notes: 'Divine Eminence: expend slot to deal extra 2d6 radiant on weapon hit. Spellcasting (WIS DC 13, +5): Guidance, Light, Sacred Flame, Thaumaturgy; Bane, Cure Wounds, Guiding Bolt, Sanctuary; Hold Person, Spiritual Weapon.',
  },
  {
    id: 'default-reef-shark',
    isDefault: true,
    name: 'Reef Shark',
    type: 'Beast',
    cr: '0.5',
    hp: 22,
    hpFormula: '4d8+4',
    ac: 12,
    speed: 0,
    abilities: { str: 14, dex: 13, con: 13, int: 1, wis: 10, cha: 4 },
    attacks: [
      { id: 'rshark-bite', name: 'Bite', hitBonus: 4, damage: '1d8+2', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Swim speed 40 ft. Blood Frenzy: advantage on melee attacks against bloodied creatures. Water Breathing only.',
  },
  {
    id: 'default-sahuagin',
    isDefault: true,
    name: 'Sahuagin',
    type: 'Humanoid',
    cr: '0.5',
    hp: 22,
    hpFormula: '4d8+4',
    ac: 12,
    speed: 30,
    abilities: { str: 13, dex: 11, con: 12, int: 12, wis: 13, cha: 9 },
    attacks: [
      { id: 'sahu-bite', name: 'Bite', hitBonus: 3, damage: '1d4+1', damageType: 'piercing', notes: '' },
      { id: 'sahu-claws', name: 'Claws', hitBonus: 3, damage: '1d4+1', damageType: 'slashing', notes: '' },
      { id: 'sahu-spear', name: 'Spear', hitBonus: 3, damage: '1d6+1', damageType: 'piercing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: Bite + Claws. Blood Frenzy: advantage on melee vs bloodied creatures. Limited Amphibiousness: breathe air and water, must submerge every 4 hours. Shark Telepathy 120 ft. Swim speed 40 ft.',
  },
  {
    id: 'default-scarecrow',
    isDefault: true,
    name: 'Scarecrow',
    type: 'Construct',
    cr: '1',
    hp: 36,
    hpFormula: '8d8',
    ac: 11,
    speed: 30,
    abilities: { str: 11, dex: 13, con: 11, int: 10, wis: 10, cha: 13 },
    attacks: [
      { id: 'scare-claws', name: 'Claws', hitBonus: 3, damage: '2d6+1', damageType: 'slashing', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: 2× Claws. Horrifying Visage: creatures within 30 ft DC 11 Wis save or frightened for 1 min. False Appearance: motionless looks like ordinary scarecrow. Vulnerable to fire. Immune to poison, psychic. Cannot be charmed, exhausted, frightened, paralyzed, poisoned, unconscious.',
  },
  {
    id: 'default-vine-blight',
    isDefault: true,
    name: 'Vine Blight',
    type: 'Plant',
    cr: '0.5',
    hp: 26,
    hpFormula: '4d8+8',
    ac: 12,
    speed: 10,
    abilities: { str: 15, dex: 8, con: 14, int: 5, wis: 10, cha: 3 },
    attacks: [
      { id: 'vblight-constrict', name: 'Constrict', hitBonus: 4, damage: '2d6+2', damageType: 'bludgeoning', notes: 'Target grappled (DC 12 escape) and restrained while grappled.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'False Appearance: motionless looks like dead shrub. Immune to blindness, deafness. Constricting Tendrils (Recharge 5–6): vines in 15-ft radius — DC 12 Str save or restrained and 2d6+2 per turn until escape.',
  },
  {
    id: 'default-wight',
    isDefault: true,
    name: 'Wight',
    type: 'Undead',
    cr: '3',
    hp: 45,
    hpFormula: '6d8+18',
    ac: 14,
    speed: 30,
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    attacks: [
      { id: 'wight-longsword', name: 'Longsword', hitBonus: 4, damage: '1d8+2', damageType: 'slashing', notes: '' },
      { id: 'wight-longbow', name: 'Longbow', hitBonus: 4, damage: '1d8+2', damageType: 'piercing', notes: 'Range 150/600 ft' },
      { id: 'wight-drain', name: 'Life Drain', hitBonus: 4, damage: '1d6+2', damageType: 'necrotic', notes: 'DC 13 Con save or max HP reduced by damage taken. Humanoid reduced to 0 HP rises as zombie.' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Multiattack: 2× Longsword or 2× Longbow, plus Life Drain. Sunlight Sensitivity: disadvantage on attacks and Perception in sunlight. Resistant to necrotic, nonmagical weapons. Immune to poison, exhaustion.',
  },
  {
    id: 'default-will-o-wisp',
    isDefault: true,
    name: "Will-o'-Wisp",
    type: 'Undead',
    cr: '2',
    hp: 22,
    hpFormula: '9d4',
    ac: 19,
    speed: 0,
    abilities: { str: 1, dex: 28, con: 10, int: 13, wis: 14, cha: 11 },
    attacks: [
      { id: 'wisp-shock', name: 'Shock', hitBonus: 4, damage: '2d8', damageType: 'lightning', notes: '' },
    ],
    spellSlots: {},
    spells: [],
    notes: 'Fly speed 50 ft (hover). Consume Life: if creature within 5 ft drops to 0, regain 10d8 HP. Ephemeral: cannot wear or carry anything. Incorporeal Movement: move through creatures/objects (5d6 force on end). Variable Illumination: bright/dim 5–20 ft. Immune to lightning, poison. Cannot be exhausted, grappled, paralyzed, poisoned, prone, restrained, unconscious.',
  },
];
